services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./app/storage/mongodb:/data/db  # ✅ Зберігаємо дані MongoDB у локальній папці

  app:
    build: .
    container_name: web_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    working_dir: /app  # Робоча директорія для додатка
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      PYTHONPATH: /app
    volumes:
      - ./app:/app  # Локальні файли програми підключені до /app
    command: ["python", "main.py"]
